"""EU AI Act transparency watcher: behavior tests on synthetic repos.

Receipts culture: every assertion rides a real SESSION run against a
fixture tree — compliant REFUTES/SUPPORTS cases, honest abstention for
non-AI repos, and the conformance kit.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from veridict.conformance import run_conformance_suite
from veridict.schemas import Claim
from veridict.watchers import run_session

from watchers.aiact_watcher import MANIFEST, SESSION


def _claim(summary, pred="aiact"):
    return Claim(claim_id="c", task_id="t", subject="s", predicate=pred,
                 scope="r", summary=summary, derived_from="d",
                 verifiability="DOCTRINAL", falsifiable_by=("watcher",),
                 critical_class=None)


def _tree(tmp_path, files: dict):
    for rel, content in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
    return str(tmp_path)


def test_conformance_kit():
    report = run_conformance_suite(SESSION)
    assert report["conformant"], [c for c in report["checks"]
                                  if not c["passed"]]


def test_plain_library_vacuous_support(tmp_path):
    """A text renderer ships no AI surface — Article 50 doesn't apply; the
    watcher says so as a vacuous SUPPORTS (house semantics: nil is a
    truthful evidence item, only unreadable references abstain)."""
    art = _tree(tmp_path, {"render.py": "def render(x): return str(x)\n",
                           "README.md": "# renderer\nfast text rendering\n"})
    ev = run_session(SESSION, _claim("transparency duties are met"),
                     "d", artifact_path=art)
    assert ev is not None and ev.stance == "SUPPORTS"
    assert "vacuous" in ev.rationale.lower()


def test_compliant_ai_repo_supports(tmp_path):
    art = _tree(tmp_path, {
        "MODEL_CARD.md": "# Model card\nfine-tuned summarizer\n",
        "model.safetensors": "weights-not-really\n",
        "training-data-summary.md": "# Summary\ncrawled CC pages 2024\n",
        "ai_outputs/summary1.txt": "This text was generated by the model.\n",
        "ai_outputs/summary1.txt.provenance.json": json.dumps(
            {"generated_by": "summarizer-v2 (veridict cert 843c4c…)",
             "generated_at": "2026-09-14T00:00:00Z"}),
    })
    ev = run_session(SESSION, _claim("transparency duties are met"),
                     "d", artifact_path=art)
    assert ev is not None and ev.stance == "SUPPORTS" and ev.tier == "W1b"


def test_missing_disclosure_refutes(tmp_path):
    art = _tree(tmp_path, {
        "app.py": "import openai\n",
        "ai_outputs/out1.txt": "synthetic text\n",
        "ai_outputs/out1.txt.provenance.json": json.dumps(
            {"generated_by": "model", "generated_at": "2026-09-01"}),
    })
    ev = run_session(SESSION, _claim("transparency duties are met"),
                     "d", artifact_path=art)
    assert ev.stance == "REFUTES"
    assert "disclosure" in ev.rationale.lower()


def test_unlabeled_output_refutes(tmp_path):
    """AI surface exists (README marks it) but an output rides without its
    machine-readable sidecar — the Art. 50 identifiability duty fails."""
    art = _tree(tmp_path, {
        "README.md": "# genai demo\noutputs are AI-generated\n",
        "ai_outputs/demo.png": "fakepixels",
    })
    ev = run_session(SESSION, _claim("transparency duties are met"),
                     "d", artifact_path=art)
    assert ev.stance == "REFUTES"
    assert "demo.png" in ev.rationale


def test_sidecar_missing_keys_refutes(tmp_path):
    art = _tree(tmp_path, {
        "AI_DISCLOSURE.md": "everything here is machine generated",
        "ai_outputs/x.txt": "hi",
        "ai_outputs/x.txt.provenance.json": json.dumps({"model": "m"}),
    })
    ev = run_session(SESSION, _claim("transparency duties are met"),
                     "d", artifact_path=art)
    assert ev.stance == "REFUTES"
    assert "generated_by" in ev.rationale


def test_weights_without_training_summary_refutes(tmp_path):
    """GPAI documentation duty: shipping weights triggers the training-data
    summary requirement."""
    art = _tree(tmp_path, {
        "MODEL_CARD.md": "# card",
        "net.onnx": "weights",
    })
    ev = run_session(SESSION, _claim("transparency duties are met"),
                     "d", artifact_path=art)
    assert ev.stance == "REFUTES"
    assert "training-data-summary" in ev.rationale


def test_manifest_contract():
    d = MANIFEST.to_dict()
    assert d["watcher_id"] == "example-aiact-transparency"
    assert d["capabilities"]["max_tier"] == "W1b"
    assert d["integrity"]["code_hash"] == \
        __import__("hashlib").sha256(open(os.path.abspath(
            os.path.join(os.path.dirname(__file__), "..", "watchers",
                         "aiact_watcher.py")), "rb").read()).hexdigest()
