#!/usr/bin/env python
"""Generate proofs/ladder/TruthTable.lean from the bounded ladder harness.

The Lean file re-checks the formal model (Ladder.lean) against ALL 28,080
recorded cases of scripts/verify_ladder.py at build time (`native_decide`):
any semantic drift between the model and the shipped Python fails the Lean
build, not just a human reading. Deterministic output: re-running this
script byte-for-byte reproduces the file, and the embedded digests tie it
to docs/receipts-ladder-verification.json (table sha256) and to the exact
veridict/ladder.py that produced it (source sha256).

Rows are packed as Nat tuples (m c p budget f evpack value div rung):
  evpack  = count·9³ + d1·9² + d2·9 + d3,  digit = tier·2+stance+1, 0 = pad
  value   0 VERIFIED 1 REFUTED 2 INCONCLUSIVE 3 ESCALATED
  div     0 UNANIMOUS 1 MAJORITY 2 SPLIT
  rung    0 R0 .. 4 R4
"""
import hashlib
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "scripts"))

import verify_ladder as VL                                # noqa: E402
from veridict.ladder import adjudicate                    # noqa: E402

VALUE = {"VERIFIED": 0, "REFUTED": 1, "INCONCLUSIVE": 2, "ESCALATED": 3}
DIV = {"UNANIMOUS": 0, "MAJORITY": 1, "SPLIT": 2}
RUNG = {"R0": 0, "R1": 1, "R2": 2, "R3": 3, "R4": 4}
TIER = {"W1a": 0, "W1b": 1, "W2": 2, "W3": 3}
STANCE = {"SUPPORTS": 0, "REFUTES": 1}
HEADER = "proofs/ladder/TruthTable.lean"


def pack_evidence(evs) -> int:
    digits = [TIER[t] * 2 + STANCE[s] + 1 for (t, s) in evs]
    digits += [0] * (3 - len(digits))
    return len(evs) * 729 + digits[0] * 81 + digits[1] * 9 + digits[2]


def main() -> int:
    rows, lean_rows = [], []
    for idx, (claim, evidence, policy, split) in enumerate(VL.cases()):
        adj = adjudicate(claim, evidence, policy, first_round_split=split)
        from dataclasses import asdict
        inp = asdict(claim) | {                      # EXACTLY the harness shape
            "evidence": [[e.tier, e.stance] for e in evidence],
            "criticality": list(policy.criticality),
            "meta_depth": policy.meta_claim_depth_budget,
            "first_round_split": split}
        rows.append({"case": idx, "input_sha256": hashlib.sha256(
            json.dumps(inp, sort_keys=True).encode()).hexdigest(),
            "value": adj.value, "divergence": adj.divergence, "rung": adj.rung})
        evs = [(e.tier, e.stance) for e in evidence]
        lean_rows.append((1 if claim.verifiability == "MACHINE_CHECKABLE" else 0,
                          1 if claim.critical_class == "CRITICAL" else 0,
                          1 if "CRITICAL" in policy.criticality else 0,
                          policy.meta_claim_depth_budget,
                          1 if split else 0,
                          pack_evidence(evs),
                          VALUE[adj.value], DIV[adj.divergence], RUNG[adj.rung]))
    table_digest = hashlib.sha256(
        json.dumps(rows, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    receipt = json.load(open(os.path.join(REPO, "docs",
                                          "receipts-ladder-verification.json")))
    assert table_digest == receipt["truth_table_sha256"], (
        "generator/harness DRIFT — regenerate the bounded receipt first "
        "(python3 scripts/verify_ladder.py) and reconcile before shipping "
        "the Lean oracle")
    src_hash = receipt["ladder_source_sha256"]

    packed = "".join(f"{m}{c}{p}{b}{f}{v}{d}{r}{ep:04d}"
                     for m, c, p, b, f, ep, v, d, r in lean_rows)
    out = f"""/-
  GENERATED by scripts/export_lean_truth_table.py — do not hand-edit.

  Machine-checked oracle for Ladder.lean: this file asserts that the Lean
  model reproduces EVERY case of the bounded verification receipt
  (docs/receipts-ladder-verification.json). The digests below tie it to
  the shipped implementation; a rebuild that disagrees fails the build.

  Rows ride as ONE string literal (10 chars each: machine, crit, polCrit,
  budget, frs, value, div, rung, evpack[4]) — cheap to elaborate, trivial
  to decode in the VM-checked proof.

  trust placement: the proofs below use `native_decide` (kernel-trusted
  compiled evaluation, as disclosed in Ladder.lean's header); the general
  invariant theorems do not rely on this file.
  ladder.py sha256 : {src_hash}
  truth-table sha256: {table_digest}
  rows: {len(lean_rows)}
-/
import Ladder

open Ladder

abbrev Row : Type := Bool × Bool × Bool × Nat × Bool × Nat × Nat × Nat × Nat

def unpackEv (evpack : Nat) : List Ev :=
  let count := evpack / 729
  let rem := evpack % 729
  let digits := [rem / 81, (rem % 81) / 9, rem % 9]
  (digits.take count).map fun (d : Nat) =>
    ((match (d - 1) / 2 with
      | 0 => Tier.w1a | 1 => Tier.w1b | 2 => Tier.w2 | _ => Tier.w3),
     if (d - 1) % 2 == 0 then Stance.supports else Stance.refutes)

def unpackVerdict : Nat → Verdict
  | 0 => .verified | 1 => .refuted | 2 => .inconclusive | _ => .escalated

def unpackDiv : Nat → Div
  | 0 => .unanimous | 1 => .majority | _ => .split

def unpackRung : Nat → Rung
  | 0 => .r0 | 1 => .r1 | 2 => .r2 | 3 => .r3 | _ => .r4

def checkRow (row : Row) : Bool :=
  let (m, c, p, b, f, ep, v, d, r) := row
  let o := adjudicate m c p b f (unpackEv ep)
  o.value == unpackVerdict v && o.div == unpackDiv d && o.rung == unpackRung r

def digit (ch : Char) : Nat := ch.toNat - 48

partial def decodeRows : List Char → List Row
  | [] => []
  | m :: c :: p :: b :: f :: v :: d :: r :: e1 :: e2 :: e3 :: e4 :: rest =>
      ((m == '1', c == '1', p == '1', digit b, f == '1',
        (digit e1 * 10 + digit e2) * 100 + (digit e3 * 10 + digit e4),
        digit v, digit d, digit r)) :: decodeRows rest
  | _ :: _ => []  -- malformed tail: impossible once rowLen pins the length

def ROWDATA : String :=
  "{packed}"

theorem rowLen : ROWDATA.length = {len(lean_rows) * 12} := by native_decide

theorem agree : List.all (decodeRows ROWDATA.toList) checkRow = true := by
  native_decide

#print axioms agree
"""
    dest = os.path.join(REPO, HEADER)
    old = open(dest).read() if os.path.exists(dest) else None
    if old == out:
        print("TruthTable.lean unchanged")
        return 0
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(out)
    print(f"wrote {HEADER} ({len(lean_rows)} rows, {len(out)//1024} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
